version: "1.0"

services:
  server:
    build:
      dockerfile: Dockerfile.${NODE_ENV}
    ports:
      - "5000:5000"

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
